CREATE TABLE IF NOT EXISTS articles (
  id BIGSERIAL PRIMARY KEY,
  author_id BIGSERIAL NOT NULL REFERENCES users(id),
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  body TEXT NOT NULL,
  favorites_count BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGSERIAL PRIMARY KEY,
  value TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tags_articles_rel (
  tag_id BIGSERIAL NOT NULL REFERENCES tags(id),
  article_id BIGSERIAL NOT NULL REFERENCES articles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorites_articles_rel (
  user_id BIGSERIAL NOT NULL REFERENCES users(id),
  article_id BIGSERIAL NOT NULL REFERENCES articles(id) ON DELETE CASCADE
);
